logging:
    level:
#        tk.mybatis: DEBUG
        com.ljkj.hr.server: DEBUG
server:
    port: 8881

spring:
    application:
        name: ace-hr-server
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non-null
    datasource:
        name: test
#        url: jdbc:mysql://localhost:3306/lj_hr_v2?useUnicode=true&characterEncoding=UTF8
        url: jdbc:mysql://192.168.1.160:3306/lj_hr_v2?useUnicode=true&characterEncoding=UTF8
#        username: root
        username: yzm
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
#        host: ${REDIS_HOST:localhost}
        host: ${REDIS_HOST:192.168.1.160}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
#        host: localhost
        host: 192.168.1.160
        port: 5672
#        username: guest
#        password: guest
        username: admin
        password: admin
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1
    
# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
    enabled: true
    base-package: com.ljkj.hr.server
    title: ace-hr-server
    version: 1.0.0.SNAPSHOT
    description: 人力资源系统服务
    contact:
        name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-hr-server
    secret: 123456
    token-header: client-token

    #redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: ${REDIS_HOST:localhost}
    port:  ${REDIS_PORT:6379}
    password:
    timeout: 2000
    # 服务或应用名
    sysName: ace-admin
    enable: true
    database: 0
# 跨服务数据合并
merge:
  enabled: true
  guavaCacheNumMaxSize: 1000
  guavaCacheRefreshWriteTime: 10 # min
  guavaCacheRefreshThreadPoolSize: 10
  aop:
    enabled: true

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: 192.168.1.161
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
            defaultZone: http://${EUREKA_HOST:192.168.1.160}:${EUREKA_PORT:8761}/eureka/

#请求和响应GZIP压缩支持
feign: 
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE
# txmanager地址
tm: 
  manager:
#    url: http://127.0.0.1:8899/tx/manager/
    url: http://192.168.1.160:8899/tx/manager/